### PR TITLE
Fix ui feedback

### LINKED ISSUE #793: UI feedback

### PR DESCRIPTION
**Pull request by idelcano**
Closes #793 
One comment about the last point. I edit the Overdue row color too(I think you maybe say never assessed but want said overdue)

### CODE REVIEW

**Comment by ifoche** [comment]
@idelcano one thing that I think I told you yesterday. I see that you chose finally to remove the tabs arrow when there's not any other arrow. There's a steady time when you press on the arrow, just before the new tab appears, that you lose the alignment. Probably the arrow addition/remove is being done later and then all the alignment is readjusted. Do you think that it is possible to avoid that effect (maybe removing/adding the arrow early in the change tab process)?

**Comment by idelcano** [comment]
@ifoche  it is true, finally i could solve it using setAlpha to make the img transparent or visible.

**Comment by ifoche** [comment]
another thing, can you also unify the appearance of every "ALL ASSESSMENT" filters (from every tab) to make them all look the same?

**Comment by idelcano** [comment]
Done !

**Pull request merged**
