### PR TITLE
Fix all assessement typo

### LINKED ISSUE #882: Planning tab "ALL ASSESSMENT" should have a final S

### PR DESCRIPTION
**Pull request by idelcano**
Closes #882

### CODE REVIEW

**Comment by ifoche** [comment]
@idelcano why are you using a string in uppercase instead of setting it to uppercase by calling toUpperCase() function? Is there any special reason for changing that?

**Comment by idelcano** [comment]
No, the reason is the string is always uppercase.
That string is only used in the filters. If we change it we need remember
set as uppercase all the places when we used that string.

I changed "all assessment" string used in the planning tab by the all
assessments string used in the other filters.

2016-03-21 12:42 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by idelcano** [comment]
@ifoche it is done.

**Comment by idelcano** [comment]
@ifoche  it is done

**Pull request merged**
