### PR TITLE
Remember the last orgUnit and the orgUnitTree

### LINKED ISSUE #640: Remember last selected OU when creating new assessment

### PR DESCRIPTION
**Pull request by idelcano**
Closes #640 
@ifoche it was crazy. The simple orgUnit was so easy. you said me it should take me about 20 minuts, and its true. 
But the org Unit hierarchy take me so time(all the day..). 

One thing.
Do you want remember the program too?
(it is comment https://github.com/EyeSeeTea/malariapp/compare/development...remember_selected_org_unit?expand=1#diff-7a3a79df21da1a54afa6fe39dbe5219aR189 ).

### CODE REVIEW

**Comment by ifoche** [comment]
Hi @idelcano. In principle just the orgUnit will be enough. Thank you

**Comment by ifoche** [comment]
Hi @idelcano, correct me if I'm wrong but this PR is still stopped as you were going to remove the program from the things that the app will remember from one survey creation to another (just orgUnit and orgUnit level) isn't it? If that's the case I'll wait for you to tell me whenever it's done before merging it.

**Comment by idelcano** [comment]
Yes @ifoche , this PR is stopped, i was looking somethings of the server and users and i will revise the code now. I was thinking in other way more simple.. i will try to do it.
I will write you a new comment when it is finish.

**Comment by ifoche** [comment]
ok, thanks

**Comment by idelcano** [comment]
@ifoche i think is ready. I removed some trash and refactor somethings. Maybe its not perfect, but It is more simple now.

**Comment by ifoche** [comment]
ok, thank you for this

**Pull request merged**
