### PR TITLE
Fragment survey assess tab

### LINKED ISSUE #672: show survey activity from assess tab

### PR DESCRIPTION
**Pull request by idelcano**
Closes #672

### CODE REVIEW

**Comment by ifoche** [comment]
@idelcano I've seen that, with this code, we've lost OrgUnit and Program from header (actionbar). Can you please set them following the image draft I attach in this comment? (forget about the colours in the actionbar, but the content). I supose that this is also happening in the improve tab, so can you change it also there? And just one last thing...can you merge development into your branch? Thank you in advance
assess_2

**Comment by ifoche** [comment]
@idelcano just a few questions:
- In the following code...

//TODO remove

//Survey survey = new Survey(orgUnit, tabGroup, Session.getUser());

//survey.save();

...why are you commenting out that? If survey is not being created there, where is that being done?

-  In the following code...

//@Subscribe

//public void onLogoutFinished(UiEvent uiEvent) {

//super.onLogoutFinished(uiEvent);

//}

...same question. why are you removing that?

- Can you rename the checkbox filenames to English names please?

**Comment by idelcano** [comment]
the first question. I dont remember do that.i  think it come from a
development branch merge.
Before the TODO we have:

Survey survey = SurveyPlanner.getInstance().startSurvey(orgUnit,tabGroup);

I think the survey is created with SurveyPlanner.


the second question, this method is not working in a fragment, I think i
can erase it, but i commented becouse i wasn t sure about it. This method
is working in DashboardActivity.

and i renamed and pushed the checkbox filenames to english(and the tab
graphics with the same problem).


2016-01-13 5:13 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by idelcano** [comment]
Ok, Looking back...

I remember comment the first lines in a merge.
I think the planning tab not use:
//Survey survey = new Survey(orgUnit, tabGroup, Session.getUser());

//survey.save();

https://github.com/EyeSeeTea/malariapp/commit/3345f5857573fb99dd2421b921dddb8eac892024

And when i merge it, i dont sure and i commented this lines.
I removed it.

About:
//@Subscribe

//public void onLogoutFinished(UiEvent uiEvent) {

//super.onLogoutFinished(uiEvent);

//}
This is not working in a fragment, but is not needed, becouse is in DashboardActivity.
I removed it.

I removed that commented lines too.

**Comment by idelcano** [comment]
Fragment transitions:
I added the fragment direction control for animate the fragment transition.

Refactor on createSurveyFragment:
I refactor the badname of setValidSurvey(restore createSurvey and extract the isValidSurvey, to checks before call the createSurvey method).

ActionBarActivity:  
Added CustomTextView to the actionbaractivity.
I use differente font for the subtitle in dashboard, the medium_font_name with only two CustomTextView looks as bold font (I needed used light_font for the subtitle).
At this moment the actionbar has two sizes, in surveyFragment, and in the dashboardactivity,

**Pull request merged**
