### PR TITLE
Persist eventsuid in db

### LINKED ISSUE #701: Persist Events UIDs in the DB

### PR DESCRIPTION
**Pull request by idelcano**
closes #701

### CODE REVIEW

**Comment by ifoche** [comment]
@idelcano did you tried to push with this code? I'm getting a 404 ERROR message

**Comment by idelcano** [comment]
@ifoche it´s true, sorry, but it is solved now(and i re-check in DB the event creation date was saved).

**Comment by ifoche** [comment]
Hi again @idelcano . I've just seen that here we would be missing one thing here. When we pull the metadata and data, we're not setting the events id in their respective surveys (in our DB), I mean, in the visitors part (https://github.com/EyeSeeTea/malariapp/blob/persist_eventsuid_in_db/app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/ConvertFromSDKVisitor.java#L304-304). Can you add this so we would have in our DB all the event ids of the previously sent surveys?

Thank you very much

**Comment by idelcano** [comment]
It is done.

**Comment by ifoche** [comment]
great! thank you very much

**Pull request merged**
