### PR TITLE
Pull on populate

### LINKED ISSUE #498: Answer + options pull

### PR DESCRIPTION
**Pull request by ivanarrizabalaga**
Closes #498

### CODE REVIEW

**Comment by ifoche** [comment]
Hi @ivanarrizabalaga 

just a few comments before accepting the PR. Can you...
- remove the .idea files from the PR
- mmm, I think is better if we just remove the dummy data generation and old conversion call from EyeSeeTeaApplication, better than commenting it. Can you do it?
- we were using, for the implementation of the Visitable iface, for each pojo, the standard pojoExtended, to clearly identify that it is the extension of the SDK model (under model subpackage). Can you rename it again to implement that naming standard?

Thanks!

**Comment by ivanarrizabalaga** [comment]
@ifoche sure!

**Comment by ivanarrizabalaga** [comment]
@ifoche done.

**Comment by ifoche** [comment]
@ivanarrizabalaga cool! Thanks

**Pull request merged**
