### PR TITLE
Progresbar wheel on match

### LINKED ISSUE #844: Add a progress bar (wheel) when a parent question is selected

### PR DESCRIPTION
**Pull request by idelcano**
Closes  #844

### CODE REVIEW

**Comment by ifoche** [comment]
@idelcano this is not working due to a misunderstanding problem. Maybe I didn't explained it properly. When I talk about parent questions, I'm not talking about match ones (btw, I'm not getting any progress wheel on match either) I was referring the questions that show/hide other questions. For example, in family planning, a parent question could be "Does this facility offer contraceptive counseling?". If you press yes there, the children questions appear. Please confirm me that you've now understood what I'm talking about. @adrianq can you explain it in Spanish to @idelcano by hangouts? Thank you very much

**Comment by idelcano** [comment]
Yes i understood and it works for my, i will revise all.

**Comment by ifoche** [comment]
ok, so if it works for you just let me check it again just in case

**Comment by idelcano** [comment]
no wait!, it works, but bad.
The problem is:
i tried in emulator and it is so fast. the progress wheel is showed AFTER the child questions was showed.
And i need do it before.
I will review it.

**Comment by ifoche** [comment]
ok, thank you for taking care of this

**Comment by idelcano** [comment]
The problem is the same as in  #845

My changes in the UI are showing after the hide/unhide childs.

I don´t understand why i can´t look my ui changes  before the UI list was reloaded.

**Comment by ifoche** [comment]
I'm going to implement the workaround of introducing a different image for selected+pressed and for non-selected+pressed. That way, although we won't see the wheel, we'll get feedback of the click. However, please continue tomorrow working on this to guess how to solve it

**Comment by idelcano** [comment]
Ok @ifoche  thanks. i will continue tomorrow. I lost all the day with this and the other issue, i look your other PR, great solution (but the dialog is showed always, when you push yes or not when the childs are visibles or not) I think the dialog should be showed only if the childs are visibles.

**Comment by idelcano** [comment]
@ifoche  sorry i was wrong yesterdey, the dialog is showed always in your solution of the other PR, it works ok!. 
I think you are working on this issue, but  i take a look.. 

I uploaded my branch, the progressbar is showed now. A little freeze, but showed when the user press a parent radiobutton and hide when the list was loaded.

**Comment by ifoche** [comment]
@idelcano it's still not working from a functional perspective. I've tested it and it takes sooooo long in a real device, and the progress bar don't even move at all. We need to analyze it better. Please, I've merged it with development. Whenever you have time it would be perfect to come back to this. It's not going to be tested in the field in Tanzania, but I would like to include it for the final R14 release (probably around the end of next week)

**Comment by ifoche** [comment]
@idelcano I'm traveling tomorrow all the day, but maybe we can meet on friday and review this task? Can you update me with the state of this task?

**Comment by idelcano** [comment]
@ifoche 
The problem now is the list method .notifyDataSetChanged().

I try to do the DB operations and score operations in background(in asyntask), and the progressbar looks good, but when we call .notifyDataSetChanged() the progressbar is gone, and the list needs 1 o 2 seconds more to refresh the items.
I will look about the notifydatasetchanged method.
I think i can finish this task today maybe.

About the friday meeting, do you know when?
If you want we can meet the saturday.

**Comment by ifoche** [comment]
@idelcano I was thinking on meeting at 16h, I just add you to the calendar event.

**Comment by idelcano** [comment]
@ifoche i uploaded this branch. I think it is more good now. It looks good in the emulator. I want try it in real device but, i dont why, all the child questions was unhidden in my phone.

**Comment by ifoche** [comment]
@idelcano I'm not approving this yet. I want to talk to you and show you the behaviour in a real device, so we can talk about it and see if there would be a solution to improve the user experience a little bit more.

**Comment by idelcano** [comment]
I didn't find a better solution
But i tested in a real device, after change the language in my phone.
i am really unhappy with the performance. I think this is not valid. In the emulator looks really better.. But in my phone... All the steps are too slow.

Maybe we need other solution like use a static image, or at least not a semi-transparent wheel. Or a progressdialog.

**Comment by ifoche** [comment]
Closing this PR as it finally didn't reach the required performance in real devices

**Pull request closed without merging**
