### PR TITLE
Push, login, logout, back to flow

### LINKED ISSUE #530: Repair app flow in visitors_try

### PR DESCRIPTION
**Pull request by ivanarrizabalaga**
Closes #530

### CODE REVIEW

**Comment by ifoche** [comment]
Hi @ivanarrizabalaga. There is just one thing missing. In HNQIS variants, server preference should be pre-set to the server URL that it has in the strings.xml. Can you please reintroduce that and upload it to this branch? Thanks

**Comment by ivanarrizabalaga** [comment]
Sure!


[image: http://]
Ivan Arrizabalaga
[image: http://]about.me/ivan-arrizabalaga
<http://about.me/ivan-arrizabalaga>

**Comment by ifoche** [comment]
Thanks, sorry but after re-reading my comment, I've seen that I had said this change was just for HNQIS, and it's for both HNQIS and EDS. In fact, there is a string in strings.xml of each variant, that points to the proper server. It's that one what we need to put in the server field of the login activity (no matter where it points to)

**Comment by ivanarrizabalaga** [comment]
Ok, understood!


[image: http://]
Ivan Arrizabalaga
[image: http://]about.me/ivan-arrizabalaga
<http://about.me/ivan-arrizabalaga>

**Comment by ivanarrizabalaga** [comment]
@ifoche new commit added to preload server url in login

**Pull request merged**
