### PR TITLE
Go to feedback button

### LINKED ISSUE #857: When a survey is marked as completed, there should be a button "Go to feedback" in the alert that tells you that the survey has been moved to improve tab

### PR DESCRIPTION
**Pull request by idelcano**
Closes #857
This need a refactor.
Go from planning tab to asses tab and open a survey has not problem, 
but go from assess tab to improve tab and load the feedback fragment yes(if the dashboardsentfragment is not loaded first, the application crash.).

I did:
Click on go to feedback.
Dashboardactivity gofeedback=true
DashboardActivity change tab to improve
improve is loaded-> tell to dashboard activity to load a feedbackfragment
dashboardactivity change the dashboardsentfragment for a feedbackfragment.
feedbackfragment set gofeedback=false;

And i need do the test.

### CODE REVIEW

**Comment by ifoche** [comment]
@idelcano can you merge development into this branch (and deal with the conflicts) and finish it (refactor and test included) ? Thanks

**Comment by ifoche** [comment]
@idelcano BTW it's not urgent, so don't work on it today, please take a rest. You've been working hard this week

**Comment by idelcano** [comment]
I finish it, i detected a bug, I think it is very strange/difficult to happen. But blocks the app . Some local surveys was saved with null completiondate.( i think this happen if the app is converting from app to the sdk and crash).
(I "fixed" it excluding the null completion date from the filters).
https://github.com/EyeSeeTea/malariapp/issues/879

**Comment by ifoche** [comment]
@idelcano would you say this is completely finished? are you happy with the code or are you willing to do a refactor?

**Comment by idelcano** [comment]
I finish but maybe it is too complex code...

The same call in planning to go to surveyfragemnt is so simple (changetab, and load survey).
But it not works with improbetab and feedbackfragment, dashboardsentfragment is more complex, and without control have some exceptions.

I don´t look other way than this ->
1 click on go_to_feedback.
2 Change of tab to improve tab.
3 Prevent the filter loads and listsload of the dashboardsentfragment
4. the dashboardsentfargment  call a method mCallback.onFeedbackInSession();
4  The dashboardactivity execute it and load the feedbackfragment with the survey in session.
5 on closeFeedbackfragment the dashboardactivity reloads the dashboardsentfragment.

Some things:
1 the dashboardsentfragment loads more fast 
2 I comment the reload of the list in dashboard becouse we was reloading the list many times(it´s necesary for control the filter load list.).
3 I cherry-pick the fix test from ivan.
4 i tried to do all independent.(without static variables from other classes).


i was thinking... maybe it is not good job becouse is very complex to do a simple action. The problem was with the filters and the listloads, and in general the dashboardsentfragment flow.

**Comment by idelcano** [comment]
@ifoche when i was explaining this in my last comment...
i think... why did i do it so complex ? 
And i take a new look and i did it more easy. 
I did a new refactor, removing the unnecesary flow.
It is finish now(test and refactor).

**Comment by idelcano** [comment]
@ifoche i checked the things that we talk about. And it's complete.
I can continue refactoring the dashboardsentfragment but is not related with this branch... (I stopped me)

**Pull request merged**
