### PR TITLE
Improve tab

### LINKED ISSUE #637: Improve Tab

### PR DESCRIPTION
**Pull request by idelcano**
At this moment, we can look the unsent completed surveys with score in the dashboardSentFragment.
closes #637

### CODE REVIEW

**Comment by ifoche** [comment]
Hi @idelcano , just one thing before merging it. Could you move the "new Select()" calls to the DB Models and call them from there? I know that we have lot of "Select" calls spreaded through the code, but we have to stop doing that, as DB interactions should be limited to the DB models. I will afford that refactor soon

**Comment by idelcano** [comment]
@ifoche  it is ready.

**Comment by ifoche** [comment]
@idelcano I'm having a bug when sorting the improve results by the orgUnit column. It is like it were ordering only from the second row on. If I press the OrgUnit column I would expect to have all the surveys that belongs to the health facility 1 together, and those belonging to health facility 2 together, but instead of that, I'm getting the first row HF1, and after that every HF2, and then the rest of the HF1...Can you replicate this bug? Can you solve it before I merge this branch?

**Comment by idelcano** [comment]
yes @ifoche i will take a look.!

**Comment by ifoche** [comment]
@idelcano I'm merging development into this branch, as it had some conflicts. I'll tell you in a few minutes but, can you then pull the changes and try again with them? I recommend you to stash your changes before pulling mine

**Comment by idelcano** [comment]
ok!

2015-12-21 12:22 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by ifoche** [comment]
Finally it was not a few minutes. It is taking so long, as I've encountered some strange problems when merging development into your branch. I'll take a look again in a couple of hours, but don't wait for me to upload the merge before. Sorry...but I'm not sure where the problem comes from

**Comment by idelcano** [comment]
Ok! 
I fixed the bug and pushed the branch. 
What problems do you have? maybe i know where look

I moved the Select() query to the db model.
i didnt read your comment before... sorry.

**Comment by ifoche** [comment]
ok, it's done and working, thanks @idelcano

**Pull request merged**
