### PR TITLE
Added new about us

### LINKED ISSUE #896: Modify the about text

### PR DESCRIPTION
**Pull request by idelcano**
Closes #896 
I added all less the table format, and the Portuguese and French languages (they still are in english).

### CODE REVIEW

**Comment by ifoche** [comment]
Ok, can you use google translator and add Portuguese and French too? table format is not necessary for the moment

**Comment by ifoche** [comment]
And sorry @idelcano but they slightly changed the text content, can you update it with the last version of the text?

**Comment by idelcano** [comment]
Yes, it is done.

**Comment by idelcano** [comment]
Wait a momment, I will merge it with development

**Comment by idelcano** [comment]
It is done.

**Pull request merged**
