### PR TITLE
Parent child

### PR DESCRIPTION
**Pull request by ivanarrizabalaga**
#346, #392

### CODE REVIEW

**Comment by ifoche** [comment]
@ivanarrizabalaga I don't know if I'm doing something wrong but it seems to me that this branch doesn't work. I've incorporated to it the last changes made to development, but if you go back to your last commit, you'll see that it didn't work anyway before those changes. I mean, I can identify 2 main problems:
- The parent-child relationships are not being detected (you can compare with master branch to check how it should look like)
- The custom tabs are crashing
Am I wrong?

**Comment by ivanarrizabalaga** [comment]
@ifoche, I did it under the hnqis variant I didnt test it for any other
variant (maybe the data is not prepared for each of them).

Anyway I will take look to see buts happening.

**Comment by ifoche** [comment]
You're absolutely right regarding custom tabs. For this release we don't have to adapt the code that is not HNQIS. My mistake. Please don't waste your time with that.

However, regarding parent-child relationships not being detected in EDS...although it is not a goal for this release, I cannot see what's so specific in HNQIS that cause EDS parent-child relationships not being shown. I think this could be revealing a problem we were not aware about.

I've just checked and going back to your last commit, HNQIS was showing its parent-child relationships, so I have introduced the bug when merging. I'll give a look to this and update you soon.

**Comment by ifoche** [comment]
@adrianq gave me the solution to EDS parent-child relationships. It was also my mistake. In the DB there are no parent-child relationships for the rest of the variants (and they weren't supposed to), sorry. Don't waste a minute with this, I'll solve the bug I introduced.

**Comment by ivanarrizabalaga** [comment]
@ifoche great news!

**Pull request merged**
