### PR TITLE
Pull test

### LINKED ISSUE #750: Create pull tests

### PR DESCRIPTION
**Pull request by idelcano**
closes #750
@ifoche before merge:

This branch comes from push_test branch (it is uploaded today).

This branch needs the fix in the sdk
[Added getter and setter for the new organisationUnit attributes](https://github.com/EyeSeeTea/dhis2-android-sdk/pull/28 )

And it is not finish, is pending:
-Test the disconnection, waiting to finish other issue. #753 
-Test 403 error, waiting to finish other issue. [#24](https://github.com/EyeSeeTea/dhis2-android-sdk/issues/24)
-Test the program attribute is not saved in app DB. At this moment is not converted to app DB.
It is only tested if it was downloaded in SDK.
-Check the orgUnitLevels.

### CODE REVIEW

**Comment by ifoche** [comment]
@idelcano does it make any sense for you?

test_pull_fail

Are you getting both tests working? (please move to 2.22 branch in sdk to test it) If I look at the logcat, I get message that apparently say that there's a communication not properly closed. Here I paste you the error message:

```
02-15 18:39:52.415 1635-1645/com.google.android.gms.persistent E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

                                                                             java.lang.Throwable: Explicit termination method 'close' not called
                                                                                 at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                                 at com.google.android.gms.org.conscrypt.Platform.closeGuardOpen(SourceFile:383)
                                                                                 at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.startHandshake(SourceFile:297)
                                                                                 at com.google.android.gms.org.conscrypt.KitKatPlatformOpenSSLSocketImplAdapter.startHandshake(SourceFile:318)
                                                                                 at com.google.android.gms.common.net.SSLCertificateSocketFactory.a(SourceFile:258)
                                                                                 at com.google.android.gms.common.net.SSLCertificateSocketFactory.createSocket(SourceFile:558)
                                                                                 at com.android.okhttp.Connection.upgradeToTls(Connection.java:171)
                                                                                 at com.android.okhttp.Connection.connect(Connection.java:151)
                                                                                 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
                                                                                 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
                                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
                                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
                                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
                                                                                 at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                                                                                 at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
                                                                                 at com.google.android.gms.http.GoogleHttpClient.a(SourceFile:948)
                                                                                 at com.google.android.gms.http.GoogleHttpClient.a(SourceFile:766)
                                                                                 at com.google.android.gms.http.GoogleHttpClient.execute(SourceFile:674)
                                                                                 at com.google.android.gms.http.GoogleHttpClient.execute(SourceFile:658)
                                                                                 at com.google.android.gms.auth.be.j.a(SourceFile:209)
                                                                                 at com.google.android.gms.auth.be.appcert.a.a(SourceFile:263)
                                                                                 at com.google.android.gms.auth.be.appcert.a.a(SourceFile:132)
                                                                                 at com.google.android.gms.auth.be.appcert.b.a(SourceFile:43)
                                                                                 at com.google.android.gms.auth.b.b.a(SourceFile:62)
                                                                                 at com.google.android.gms.auth.b.a.a(SourceFile:120)
                                                                                 at com.google.android.gms.auth.b.a.a(SourceFile:61)
                                                                                 at com.google.android.gms.auth.be.cron.AuthCronService.a(SourceFile:44)
                                                                                 at com.google.android.gms.gcm.au.run(SourceFile:140)
02-15 18:39:52.415 1635-1645/com.google.android.gms.persistent E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                             java.lang.Throwable: Explicit termination method 'end' not called
                                                                                 at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                                 at java.util.zip.Inflater.<init>(Inflater.java:82)
                                                                                 at com.android.okio.GzipSource.<init>(GzipSource.java:57)
                                                                                 at com.android.okhttp.internal.http.HttpEngine.initContentStream(HttpEngine.java:478)
                                                                                 at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:668)
                                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:379)
                                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
                                                                                 at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
                                                                                 at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                                                                                 at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
                                                                                 at com.google.android.gms.http.GoogleHttpClient.a(SourceFile:802)
                                                                                 at com.google.android.gms.http.GoogleHttpClient.a(SourceFile:767)
                                                                                 at com.google.android.gms.http.GoogleHttpClient.execute(SourceFile:674)
                                                                                 at com.google.android.gms.http.GoogleHttpClient.execute(SourceFile:658)
                                                                                 at com.google.android.gms.auth.be.j.a(SourceFile:209)
                                                                                 at com.google.android.gms.auth.be.appcert.a.a(SourceFile:263)
                                                                                 at com.google.android.gms.auth.be.appcert.a.a(SourceFile:132)
                                                                                 at com.google.android.gms.auth.be.appcert.b.a(SourceFile:43)
                                                                                 at com.google.android.gms.auth.b.b.a(SourceFile:62)
                                                                                 at com.google.android.gms.auth.b.a.a(SourceFile:120)
                                                                                 at com.google.android.gms.auth.b.a.a(SourceFile:61)
                                                                                 at com.google.android.gms.auth.be.cron.AuthCronService.a(SourceFile:44)
                                                                                 at com.google.android.gms.gcm.au.run(SourceFile:140)

```

**Comment by idelcano** [comment]
It works for me but.... I think i runing my test in a bad way, becouse i
executed all the test one by one (And i testing in the emulator).

I don´t run all the test at same time.
For execute all at same time, you clicked in test folder and run, correct?
It is the correct way?
I will take a look.

2016-02-15 18:57 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by ifoche** [comment]
What I did is create a new configuration...

test_configuration

...to execute all tests in module 'app'...

test_configuration_2

 I've tried both defining the runner (as people from Espresso library say) and without doing it, and same result. I've never executed the test alone...but I suppose that if we want to automate the test launch, we cannot rely on manual execution of the tests one by one. However, I've executed the test alone and it continues failing. The point there may be that in my case, pull is being done very quickly so when you're trying to press on the cancel button it's not there anymore...does it make any sense for you?

**Comment by idelcano** [comment]
Yes i think it is the problem.
I will re-check  and fix all and anwser you. Thanks @ifoche

2016-02-15 19:54 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by ifoche** [comment]
Thank you for taking care of it.

**Comment by idelcano** [comment]
Sorry @ifoche  It take me more time than expected..
Finally, i only find this solution, add waitforpull in the logintest:

https://github.com/EyeSeeTea/malariapp/pull/761/files#diff-6551abb6a7edcf8b96aaf927b7e45b56R104

The problem is:
if you doing the login test without cancel or finish the pull, when you run the cancel test the pull of the loging show the dialog "pull completed"(maybe is working on background?). 

It is solved waiting for finish the pull. But maybe we need fix it in the code.


I decrease the seconds to loging, and for click on cancel too.

**Comment by ifoche** [comment]
ok, it seems now we're closer to the solution (see the picture) with that workaround. I can now see more working tests, but still some tests are not being able to make it. BTW, Espresso guys have also a library specially dedicated to deal with background resources and those things (that would imply adding androidTestCompile "com.android.support.test.espresso:espresso-idling-resource:$rootProject.ext.espressoVersion" to gradle). Maybe we need to start using it?

pull_tests_feedback

Trace for pullCancelledReturnsLogin is:
```
junit.framework.AssertionFailedError: expected:<class org.eyeseetea.malariacare.LoginActivity> but was:<class org.eyeseetea.malariacare.ProgressActivity>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at org.eyeseetea.malariacare.test.pull.PullCancelTest.pullCancelledReturnsLogin(PullCancelTest.java:54)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
```

Trace for pushWithOutPermissionsDoesNOTPush:
```
android.support.test.espresso.PerformException: Error performing 'single click' on view 'with id: org.eyeseetea.malariacare.hnqispull:id/plusButton'.
at android.support.test.espresso.PerformException$Builder.build(PerformException.java:83)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:70)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:53)
at android.support.test.espresso.ViewInteraction.runSynchronouslyOnUiThread(ViewInteraction.java:184)
at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:115)
at android.support.test.espresso.ViewInteraction.perform(ViewInteraction.java:87)
at org.eyeseetea.malariacare.test.utils.SDKTestUtils.startSurvey(SDKTestUtils.java:130)
at org.eyeseetea.malariacare.test.push.PushErrorTest.pushWithOutPermissionsDoesNOTPush(PushErrorTest.java:67)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.eyeseetea.malariacare.database.model.Program.equals(java.lang.Object)' on a null object reference
at org.eyeseetea.malariacare.fragments.CreateSurveyFragment.filterPrograms(CreateSurveyFragment.java:553)
at org.eyeseetea.malariacare.fragments.CreateSurveyFragment.access$600(CreateSurveyFragment.java:71)
at org.eyeseetea.malariacare.fragments.CreateSurveyFragment$OrgUnitSpinnerListener.onItemSelected(CreateSurveyFragment.java:471)
at android.widget.AdapterView.fireOnSelected(AdapterView.java:897)
at android.widget.AdapterView.access$200(AdapterView.java:48)
at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:865)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:467)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:408)
at android.support.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:393)
at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:44)
at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:98)
at android.support.test.espresso.ViewInteraction$1.run(ViewInteraction.java:144)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Trace for pushWithPermissionsDoesPush:
```
android.support.test.espresso.PerformException: Error performing 'single click' on view 'with id: org.eyeseetea.malariacare.hnqispull:id/plusButton'.
at android.support.test.espresso.PerformException$Builder.build(PerformException.java:83)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:70)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:53)
at android.support.test.espresso.ViewInteraction.runSynchronouslyOnUiThread(ViewInteraction.java:184)
at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:115)
at android.support.test.espresso.ViewInteraction.perform(ViewInteraction.java:87)
at org.eyeseetea.malariacare.test.utils.SDKTestUtils.startSurvey(SDKTestUtils.java:130)
at org.eyeseetea.malariacare.test.push.PushOKTest.pushWithPermissionsDoesPush(PushOKTest.java:78)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.eyeseetea.malariacare.database.model.Program.equals(java.lang.Object)' on a null object reference
at org.eyeseetea.malariacare.fragments.CreateSurveyFragment.filterPrograms(CreateSurveyFragment.java:553)
at org.eyeseetea.malariacare.fragments.CreateSurveyFragment.access$600(CreateSurveyFragment.java:71)
at org.eyeseetea.malariacare.fragments.CreateSurveyFragment$OrgUnitSpinnerListener.onItemSelected(CreateSurveyFragment.java:471)
at android.widget.AdapterView.fireOnSelected(AdapterView.java:897)
at android.widget.AdapterView.access$200(AdapterView.java:48)
at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:865)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:467)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:408)
at android.support.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:393)
at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:44)
at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:98)
at android.support.test.espresso.ViewInteraction$1.run(ViewInteraction.java:144)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

However, I cannot really understand why aren't you getting the same errors than me.

**Comment by idelcano** [comment]
Are you trying in real device? maybe the problem is i was trying in
emulators, and it was more slow

And i dont use pushWithPermissionsDoesPush and
pushWithOutPermissionsDoesNOTPush, are  they finished? maybe i need merge
the push_test branch again for solve this two errors.

2016-02-16 1:53 GMT+01:00 Ignacio Foche <notifications@github.com>:

**Comment by ifoche** [comment]
In fact I'm trying on the default Android emulator. Maybe my computer here is a bit faster, or something like that. Regarding the push tests, you're right, those are not your tests. Forget about them. But pullCancelledReturnsLogin is yours, isn't it? Do you have any clue about why is that tests failing?

**Comment by idelcano** [comment]
I was trying with genymotion emulator(and it works), but i have the same problem than you un android emulator(more slow transitions?) 
I added a thread sleep in pullcancell test and it works for me in android emulator and genymotion emulator.

Pull cancel test in genymotion:  11.8 secs
Pull cancel test in android emulator  13.837sevs

**Comment by ifoche** [comment]
@idelcano just to be sure, you were going to refactor these tests to adapt them to the tests standard structure, and after that you will tell me by here in order for me to merge them, is it correct?

**Comment by idelcano** [comment]
Yes @ifoche . One thing, 
Can i finish the other issue?
Or it should be ready before eds issue.

**Comment by ifoche** [comment]
@idelcano that depends on how long eds issue would take. Tests are important to be running and operative by the end of this week/beginning next week. If you think eds issue will be prepared before that, is ok.

**Pull request merged**
