### PR TITLE
Main score stored in db, empty surveys not sent

### LINKED ISSUE #414: Analyse if we should persist the overall score

### PR DESCRIPTION
**Pull request by ivanarrizabalaga**
Closes #414, #427, #509.

### CODE REVIEW

**Comment by ifoche** [comment]
@ivanarrizabalaga . This code introduces a bug when deleting a sent survey. It produces a crash (you can it in crashlytics). Apparently it is related to a foreign key, and it looks like related to the new Score table. Can you give a look to this? Thank you in advance

**Comment by ivanarrizabalaga** [comment]
Sure, my fault. The code tries to delete the survey wihout deleting its
score first.

Now I'm out in the street, is it ok if I push the fix around 22h?

**Comment by ifoche** [comment]
Ok, I'll leave it there without merging it until that time, thanks

**Comment by ifoche** [comment]
@ivanarrizabalaga You've just told me that you've uploaded the fix to the bug, but no commit appears on github, did you do it into the main_score branch, did you forget to push it?

**Pull request merged**
