### PR TITLE
Dashboard charts

### LINKED ISSUE #456: Create new monitoring section layout (in dashboard activity)

### PR DESCRIPTION
**Pull request by ivanarrizabalaga**
Closes #456, #457, #458, #459.

I've added a scroll for the webview to help the visualization but a general scroll is still a must.

### CODE REVIEW

**Comment by ifoche** [comment]
Trying it on a 4.2.2 virtual device, charts are not shown. Have you tested it before on this kind of device?

**Comment by ifoche** [comment]
on 4.4.2 real device is not working either.

**Comment by ivanarrizabalaga** [comment]
Nop, sorry.

In order to know whats happening when the app is running try on your chrome
brower:

chrome://inspect

Click to debug the browser inside your emulator or device check for some
javascript errors.

Probably some of the javascript is not compatible with the version that
runs thw webview for older devices.

**Comment by ifoche** [comment]
But I think that must not be the problem, because I'm trying in a 5.0 device right now it doesn't work, maybe you forgot to upload something?

**Comment by ivanarrizabalaga** [comment]
I will take a look tonight dont worry

**Comment by ifoche** [comment]
thank you very much

**Pull request merged**
