### PR TITLE
Screen switches off crash

### LINKED ISSUE #585: When pull is in a real device and the screen switches off, an exception is thrown

### PR DESCRIPTION
**Pull request by idelcano**
@ifoche 
Added pulling control with preferenceshared (if you don´t like i remove it).
Fixed the progresactivity dialog as models dialog.
closes #585

### CODE REVIEW

**Comment by ifoche** [comment]
@idelcano sorry about asking this but, what is the point of making a difference between the first pull and the rest of the pulls? I mean, why are we storing "incompleted_pull", "first_pull" and "completed_pull" and not only a boolean variable "pull_in_progress" with "true" or "false"? Sorry if it is too clear, I didn't meditate it too long

**Comment by idelcano** [comment]
True and true. It should be called pull, no first pull.
And true, i will remove it and use boolean value.
I dont use it becouse  i cant  save  boolean  in a String type
(getstring/putstring) obviusly ... i forget i can save boolean type in
shared preferences.
Totally true. Sorry!

**Comment by idelcano** [comment]
it is fixed.

I think it makes more sense to use "pull_metadata" that "pull_in_progress"
Because when we launching the application,the value "pull_in_progress" should be true and this is not true, however, if "pull_metadata" is false, it is true....

I fixed using pull_metadata variable name.
Anyway, if you want i use pull_in_progress.

**Comment by idelcano** [comment]
I fixed other problem.. I think is related.. and it could be in this branch.

If you press outside of the dialog, the activity dont do nothing and the dialog disappeared.
I make the dialog as model dialog.(only add setcancelable(false)).

**Comment by ifoche** [comment]
Thank you very much! The code looks very nice.

**Pull request merged**
