### PR TITLE
Separate composite scores

### LINKED ISSUE #554: Pull CompositeScore & separate them from Questions

### PR DESCRIPTION
**Pull request by ivanarrizabalaga**
Closes #554

### CODE REVIEW

**Comment by ifoche** [comment]
@ivanarrizabalaga I think we can omit the AttributeValueHelper class by introducing its methods into the pojos, as we were doing before, can you do it? is there any reason I'm not seeing now that avoids that?

**Comment by ivanarrizabalaga** [comment]
@ifoche, @idelcano attributevaluehelper methods moved into each extended pojo for consistency.

**Comment by ifoche** [comment]
@ivanarrizabalaga thank you very much, @idelcano, I'm going to merge it into visitors_try, after that, can you after that merge visitors_try into your branch? I'll tell when it's done

**Comment by ifoche** [comment]
@idelcano ok, it's done, you can merge it now from visitors_try

**Comment by idelcano** [comment]
Ok!

**Pull request merged**
