### PR TITLE
Remove tabgroups

### LINKED ISSUE #1101: remove tabgroup from domains

### PR DESCRIPTION
**Pull request by ivanarrizabalaga**
Closes #1101

### CODE REVIEW

**Comment by ifoche** [comment]
@ivanarrizabalaga I'm trying to push using this code and getting the following errors:
- [ ] The survey is always with a preceding asterisk, like if could send the survey
- [ ] The app sometimes crash at the end of the push
- [ ] When you look at the server, the values are not there (I'm testing using Test HF 1 and Adherence program), and not only that, we're submitting a lot of blank surveys in its place

Can you please take a look at this?

Thanks

```
07-03 11:18:18.894 28609-28609/org.eyeseetea.malariacare.eds_bb E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: org.eyeseetea.malariacare.eds_bb, PID: 28609
                                                                                  java.lang.RuntimeException: Could not dispatch event: class org.eyeseetea.malariacare.database.iomodules.dhis.importer.SyncProgressStatus to handler [EventHandler public void org.eyeseetea.malariacare.ProgressActivity.onProgressChange(org.eyeseetea.malariacare.database.iomodules.dhis.importer.SyncProgressStatus)]: Unable to add window -- token android.os.BinderProxy@4274c618 is not valid; is your activity running?
                                                                                      at com.squareup.otto.Bus.throwRuntimeException(Bus.java:458)
                                                                                      at com.squareup.otto.Bus.dispatch(Bus.java:388)
                                                                                      at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
                                                                                      at com.squareup.otto.Bus.post(Bus.java:338)
                                                                                      at org.hisp.dhis.android.sdk.utils.MainThreadBus.access$001(MainThreadBus.java:41)
                                                                                      at org.hisp.dhis.android.sdk.utils.MainThreadBus$1.run(MainThreadBus.java:56)
                                                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:146)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5598)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                                   Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4274c618 is not valid; is your activity running?
                                                                                      at android.view.ViewRootImpl.setView(ViewRootImpl.java:771)
                                                                                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:278)
                                                                                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                                                      at android.app.Dialog.show(Dialog.java:289)
                                                                                      at org.eyeseetea.malariacare.ProgressActivity.showException(ProgressActivity.java:261)
                                                                                      at org.eyeseetea.malariacare.ProgressActivity.access$100(ProgressActivity.java:54)
                                                                                      at org.eyeseetea.malariacare.ProgressActivity$2.run(ProgressActivity.java:200)
                                                                                      at android.app.Activity.runOnUiThread(Activity.java:4931)
                                                                                      at org.eyeseetea.malariacare.ProgressActivity.onProgressChange(ProgressActivity.java:196)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
                                                                                      at com.squareup.otto.Bus.dispatch(Bus.java:386)
                                                                                      at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369) 
                                                                                      at com.squareup.otto.Bus.post(Bus.java:338) 
                                                                                      at org.hisp.dhis.android.sdk.utils.MainThreadBus.access$001(MainThreadBus.java:41) 
                                                                                      at org.hisp.dhis.android.sdk.utils.MainThreadBus$1.run(MainThreadBus.java:56) 
                                                                                      at android.os.Handler.handleCallback(Handler.java:733) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                      at android.os.Looper.loop(Looper.java:146) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5598) 
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                                      at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by ivanarrizabalaga** [comment]
Sure, I will check it out.
Is the tabgroups branch updated with the merge in progress??

**Comment by ivanarrizabalaga** [comment]
Several pushes are being created due to a conflict with some push data:

```json
{
	"httpStatus": "Conflict",
	"httpStatusCode": 409,
	"status": "WARNING",
	"message": "One more conflicts encountered, please check import summary.",
	"response": {
		"responseType": "ImportSummaries",
		"imported": 18,
		"updated": 0,
		"deleted": 0,
		"ignored": 2,
		"importSummaries": [{
			"responseType": "ImportSummary",
			"status": "SUCCESS",
			"importCount": {
				"imported": 18,
				"updated": 0,
				"ignored": 2,
				"deleted": 0
			},
			"conflicts": [{
				"object": "govBhUWmNEU",
				"value": "value_not_valid_date"
			}, {
				"object": "i8eExBp1Qev",
				"value": "value_not_valid_date"
			}],
			"reference": "zpE7QBZ5nJv",
			"href": "https://ken.malariaotss.org/api/events/zpE7QBZ5nJv"
		}]
	}
}
```

**Comment by ivanarrizabalaga** [comment]
@ifoche I've just pushed the fixes for #1106 and #1107, now it should be working ok

**Pull request merged**
